version: '3.8'
services:
  genflow-frontend:
    build: 
      context: ../../../frontend
    ports:
      - "6060:6060"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:6060
      - CREWAI_API_URL=http://genflow-backend:8080
    depends_on:
      - genflow-backend

  genflow-backend:
    build:
      context: ../../../backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../../../backend:/app

  langmanus-web:
    build:
      context: ../../../integrations/langmanus-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://langmanus-api:8000
    depends_on:
      - langmanus-api

  langmanus-api:
    build:
      context: ../../../integrations/langmanus
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}